import { pool } from '../database/db.js';
import type { Campaign, CampaignDelivery, CampaignDraftInput, CampaignEventType } from '../types/campaign.js';

interface CampaignRow { id: string; merchant_id: string; name: string; objective: Campaign['objective']; status: Campaign['status']; audience: Record<string, unknown>; product_ids: string[]; content: Record<string, unknown>; schedule_at: Date | null; approved_at: Date | null; created_at: Date; updated_at: Date; }
function map(row: CampaignRow): Campaign { return { id: row.id, merchantId: row.merchant_id, name: row.name, objective: row.objective, status: row.status, audience: row.audience, productIds: row.product_ids ?? [], content: row.content, scheduleAt: row.schedule_at, approvedAt: row.approved_at, createdAt: row.created_at, updatedAt: row.updated_at }; }

export class CampaignRepository {
  async create(merchantId: string, input: CampaignDraftInput): Promise<Campaign> {
    const result = await pool.query<CampaignRow>(`INSERT INTO campaigns (merchant_id, name, objective, audience, product_ids, content, schedule_at, status) VALUES ($1, $2, $3, $4, $5, $6, $7, 'DRAFT') RETURNING *`, [merchantId, input.name, input.objective, input.audience, JSON.stringify(input.productIds), input.content ?? {}, input.scheduleAt ?? null]);
    return map(result.rows[0] as CampaignRow);
  }
  async list(merchantId: string): Promise<Campaign[]> { const result = await pool.query<CampaignRow>('SELECT * FROM campaigns WHERE merchant_id = $1 ORDER BY created_at DESC', [merchantId]); return result.rows.map(map); }
  async get(id: string, merchantId: string): Promise<Campaign | null> { const result = await pool.query<CampaignRow>('SELECT * FROM campaigns WHERE id = $1 AND merchant_id = $2', [id, merchantId]); return result.rows[0] ? map(result.rows[0]) : null; }
  async approve(id: string, merchantId: string): Promise<Campaign | null> { const result = await pool.query<CampaignRow>(`UPDATE campaigns SET status = 'APPROVED', approved_at = now() WHERE id = $1 AND merchant_id = $2 AND status IN ('DRAFT', 'PENDING_APPROVAL') RETURNING *`, [id, merchantId]); return result.rows[0] ? map(result.rows[0]) : null; }
  async schedule(id: string, merchantId: string): Promise<Campaign | null> { const result = await pool.query<CampaignRow>(`UPDATE campaigns SET status = 'SCHEDULED' WHERE id = $1 AND merchant_id = $2 AND status = 'APPROVED' RETURNING *`, [id, merchantId]); return result.rows[0] ? map(result.rows[0]) : null; }
  async createRun(id: string): Promise<string> { const result = await pool.query<{ id: string }>(`INSERT INTO campaign_runs (campaign_id, status, started_at) VALUES ($1, 'RUNNING', now()) RETURNING id`, [id]); return (result.rows[0] as { id: string }).id; }
  async queueDelivery(runId: string, recipientId: string, productId: string, idempotencyKey: string): Promise<CampaignDelivery> { const result = await pool.query<{ id: string; run_id: string; recipient_id: string; product_id: string; idempotency_key: string; status: CampaignDelivery['status']; attempts: number; provider_reference: string | null; last_error: string | null }>(`INSERT INTO campaign_deliveries (run_id, recipient_id, product_id, idempotency_key) VALUES ($1, $2, $3, $4) ON CONFLICT (idempotency_key) DO UPDATE SET idempotency_key = EXCLUDED.idempotency_key RETURNING *`, [runId, recipientId, productId, idempotencyKey]); const row = result.rows[0] as (typeof result.rows)[number]; return { id: row.id, runId: row.run_id, recipientId: row.recipient_id, productId: row.product_id, idempotencyKey: row.idempotency_key, status: row.status, attempts: row.attempts, providerReference: row.provider_reference, lastError: row.last_error }; }
  async recordEvent(campaignId: string, eventType: CampaignEventType, input: { runId?: string; recipientId?: string; productId?: string; metadata?: Record<string, unknown> } = {}): Promise<void> { await pool.query(`INSERT INTO campaign_events (campaign_id, run_id, recipient_id, product_id, event_type, metadata) VALUES ($1, $2, $3, $4, $5, $6)`, [campaignId, input.runId ?? null, input.recipientId ?? null, input.productId ?? null, eventType, input.metadata ?? {}]); }
}
