import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { apiGet, apiPost } from '../services/apiClient';

interface CartItem { productId: string; name: string; quantity: number; unitPrice: string; currency: string; subtotal: string; }
interface Cart { items: CartItem[]; subtotal: string; currency: string; }
interface Order { id: string; status: string; paymentStatus: string; totalAmount: string; currency: string; items: CartItem[]; createdAt: string; razorpayPaymentId?: string | null; }
interface RazorpayResponse { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string; }
interface RazorpayOptions { key: string; amount: number; currency: string; name: string; order_id: string; handler: (response: RazorpayResponse) => void; modal: { ondismiss: () => void }; }
interface RazorpayCheckout { open: () => void; on: (event: 'payment.failed', handler: (event: { error: { description?: string } }) => void) => void; }
declare global { interface Window { Razorpay?: new (options: RazorpayOptions) => RazorpayCheckout; } }
export function CheckoutPage() {
  const { token } = useAuth(); const navigate = useNavigate(); const [cart, setCart] = useState<Cart | null>(null); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (token) void apiGet<Cart>('/cart', token).then(setCart).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load cart')); }, [token]);
  async function checkout() { if (!token) return; setSubmitting(true); setError(''); try { const created = await apiPost<{ order: Order }>('/orders/checkout', undefined, token); const payment = await apiPost<{ keyId: string; razorpayOrderId: string; amount: number; currency: string; orderId: string }>('/payments/create-order', { orderId: created.order.id }, token); if (!window.Razorpay) throw new Error('Razorpay Checkout is unavailable'); const razorpay = new window.Razorpay({ key: payment.keyId, amount: payment.amount, currency: payment.currency, name: 'AIsle', order_id: payment.razorpayOrderId, modal: { ondismiss: () => setSubmitting(false) }, handler: (paymentResponse) => { void apiPost<{ order: Order }>('/payments/verify', { orderId: payment.orderId, razorpayOrderId: paymentResponse.razorpay_order_id, razorpayPaymentId: paymentResponse.razorpay_payment_id, razorpaySignature: paymentResponse.razorpay_signature }, token).then((verified) => navigate(`/buyer/orders/${verified.order.id}`, { state: { order: verified.order, confirmation: true } })).catch((reason) => setError(reason instanceof Error ? reason.message : 'Payment verification failed')).finally(() => setSubmitting(false)); } }); razorpay.on('payment.failed', (event) => { void apiPost<{ order: Order }>('/payments/failure', { orderId: payment.orderId, razorpayOrderId: payment.razorpayOrderId }, token).then(() => setError(event.error.description ?? 'Payment failed')).catch((reason) => setError(reason instanceof Error ? reason.message : 'Payment failed')).finally(() => setSubmitting(false)); }); razorpay.open(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Checkout failed'); setSubmitting(false); } }
  if (!cart) return <p className="text-sm text-slate-500">Loading checkout...</p>;
  return <section className="grid gap-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-saffron">Checkout</p><h1 className="mt-2 text-3xl font-semibold">Review your order</h1></div>{error ? <p className="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}{cart.items.length === 0 ? <div className="border border-slate-200 bg-white p-6">Your cart is empty. <Link className="font-semibold text-mint" to="/buyer">Continue shopping</Link></div> : <div className="max-w-2xl border border-slate-200 bg-white p-6"><div className="grid gap-3">{cart.items.map((item) => <div className="flex justify-between gap-4 border-b border-slate-100 pb-3" key={item.productId}><span>{item.name} × {item.quantity}</span><strong>{item.currency} {Number(item.subtotal).toLocaleString('en-IN')}</strong></div>)}</div><p className="mt-5 flex justify-between text-lg"><span>Total</span><strong>{cart.currency} {Number(cart.subtotal).toLocaleString('en-IN')}</strong></p><button type="button" disabled={submitting} onClick={() => void checkout()} className="mt-5 w-full bg-ink px-4 py-3 text-sm font-semibold text-white disabled:bg-slate-400">{submitting ? 'Opening payment...' : `Pay ${cart.currency} ${Number(cart.subtotal).toLocaleString('en-IN')}`}</button></div>}</section>;
}