import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { apiGet, apiPost } from '../services/apiClient';
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, SectionHeading, StatusBadge } from '../components/ui';

interface CartItem { productId: string; name: string; quantity: number; subtotal: string; }
interface Cart { items: CartItem[]; subtotal: string; currency: string; }
interface Order { id: string; status: string; paymentStatus: string; totalAmount: string; currency: string; }
interface Approval { id: string; amount: number; currency: string; status: string; expiresAt: string; }
interface RazorpayResponse { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string; }
interface RazorpayOptions { key: string; amount: number | string; currency: string; name: string; order_id: string; handler: (response: RazorpayResponse) => void; modal: { ondismiss: () => void }; }
interface RazorpayCheckout { open: () => void; on: (event: 'payment.failed', handler: (event: { error: { description?: string } }) => void) => void; }
declare global { interface Window { Razorpay?: new (options: RazorpayOptions) => RazorpayCheckout; } }

export function CheckoutPage() {
  const { token } = useAuth(); const navigate = useNavigate();
  const [cart, setCart] = useState<Cart | null>(null); const [approval, setApproval] = useState<Approval | null>(null); const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [paymentState, setPaymentState] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!token) return; void apiGet<Cart>('/cart', token).then(setCart).catch(() => setError('We could not load your cart. Try again from the cart page.')).finally(() => setLoading(false)); }, [token]);

  async function requestApproval() { if (!token) return; setBusy(true); setError(''); try { const result = await apiPost<{ approval: Approval }>('/approvals', { action: 'PURCHASE' }, token); setApproval(result.approval); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Approval could not be requested.'); } finally { setBusy(false); } }
  async function decideApproval(decision: 'approve' | 'reject') { if (!token || !approval) return; setBusy(true); setError(''); try { await apiPost(`/approvals/${approval.id}/${decision}`, undefined, token); if (decision === 'reject') setApproval(null); else await createOrder(approval.id); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Approval status could not be updated. The cart may have changed.'); } finally { setBusy(false); } }
  async function createOrder(approvalId?: string) { if (!token) return; setBusy(true); setError(''); try { const result = await apiPost<{ order: Order }>('/orders/checkout', approvalId ? { approvalId } : undefined, token); setOrder(result.order); await openPayment(result.order); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Checkout could not be completed.'; if (/approval|required|policy/i.test(message)) { setApproval(null); setError('This purchase needs a fresh approval before an order can be created.'); } else if (/stock|active|available/i.test(message)) setError('A product changed availability. Review your cart before trying again.'); else setError('Checkout could not be completed. Please review your cart and try again.'); } finally { setBusy(false); } }
  async function openPayment(existingOrder: Order) { if (!token) return; if (!window.Razorpay) { setPaymentState('failed'); setError('Payment checkout is unavailable right now. You can retry from this order later.'); return; } setPaymentState('pending'); try { const payment = await apiPost<{ keyId: string; razorpayOrderId: string; amount: number | string; currency: string; orderId: string }>('/payments/create-order', { orderId: existingOrder.id }, token); const razorpay = new window.Razorpay({ key: payment.keyId, amount: payment.amount, currency: payment.currency, name: 'AIsle', order_id: payment.razorpayOrderId, modal: { ondismiss: () => { setPaymentState('pending'); setBusy(false); } }, handler: (response) => { void apiPost<{ order: Order }>('/payments/verify', { orderId: existingOrder.id, razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature }, token).then((result) => { setOrder(result.order); setPaymentState('success'); setTimeout(() => navigate(`/buyer/orders/${result.order.id}`, { state: { order: result.order, confirmation: true } }), 500); }).catch(() => { setPaymentState('failed'); setError('Payment verification failed. Your order was not confirmed. Retry payment safely.'); }).finally(() => setBusy(false)); } }); razorpay.on('payment.failed', (event) => { void apiPost<{ order: Order }>('/payments/failure', { orderId: existingOrder.id, razorpayOrderId: payment.razorpayOrderId }, token).then((result) => { setOrder(result.order); setPaymentState('failed'); setError(event.error.description ?? 'Payment failed. Your order has not been confirmed.'); }).catch(() => { setPaymentState('failed'); setError('Payment failed. Check the order status before retrying.'); }).finally(() => setBusy(false)); }); razorpay.open(); } catch { setPaymentState('failed'); setError('Payment could not be started. Your order remains retryable.'); setBusy(false); } }
  async function retryPayment() { if (!token || !order) return; setBusy(true); setError(''); try { await apiPost(`/payments/${order.id}/retry`, undefined, token); await openPayment({ ...order, status: 'PENDING', paymentStatus: 'PENDING' }); } catch { setPaymentState('failed'); setError('Payment retry could not start. Please check your order status and try again.'); setBusy(false); } }
  if (loading) return <LoadingState label="Loading your live cart..." />;
  if (!cart) return <ErrorState message={error || 'Cart unavailable.'} />;
  if (!cart.items.length) return <EmptyState title="Your cart is empty" message="Find something useful with the buyer assistant first." action={<Link className="button button-primary" to="/buyer">Continue shopping</Link>} />;
  return <section className="grid gap-7"><SectionHeading eyebrow="Buyer checkout" title="Review, approve, then pay"><Link className="text-sm font-bold text-mint" to="/buyer/cart">Edit cart</Link></SectionHeading>
    {error ? <div className="error-state state-box"><strong>{paymentState === 'failed' ? 'Payment needs attention' : 'Checkout needs attention'}</strong><span>{error}</span>{paymentState === 'failed' && order ? <Button onClick={() => void retryPayment()} disabled={busy}>Retry payment</Button> : null}{error.includes('fresh approval') ? <Button variant="secondary" onClick={() => void requestApproval()} disabled={busy}>Request new approval</Button> : null}</div> : null}
    {approval ? <Card className="border-amber-200 bg-amber-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone="warning">Approval required</Badge><h2 className="mt-3 font-serif text-2xl">Confirm this purchase</h2><p className="mt-2 max-w-xl text-sm text-slate-600">The backend policy requires your explicit approval. This is not an automatic AI action.</p></div><StatusBadge status={approval.status} /></div><div className="mt-5 grid gap-2 border-t border-amber-200 pt-4 text-sm sm:grid-cols-3"><p><span className="block text-slate-500">Action</span><strong>Purchase cart</strong></p><p><span className="block text-slate-500">Authoritative amount</span><strong>{approval.currency} {approval.amount.toFixed(2)}</strong></p><p><span className="block text-slate-500">Valid until</span><strong>{new Date(approval.expiresAt).toLocaleTimeString()}</strong></p></div><div className="mt-5 flex flex-wrap gap-3"><Button disabled={busy} onClick={() => void decideApproval('approve')}>Approve purchase</Button><Button variant="secondary" disabled={busy} onClick={() => void decideApproval('reject')}>Reject</Button></div></Card> : null}
    {order ? <Card className="grid gap-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Order created</p><h2 className="mt-1 font-serif text-2xl">Payment status</h2></div><StatusBadge status={paymentState === 'success' ? 'PAID' : paymentState === 'failed' ? 'FAILED' : order.paymentStatus} /></div><p className="text-sm text-slate-600">Order {order.id} remains unconfirmed until the backend verifies payment.</p>{paymentState === 'success' ? <p className="text-sm font-semibold text-emerald-700">Payment confirmed. Opening your order...</p> : paymentState === 'pending' ? <p className="text-sm text-amber-700">Payment is pending in Razorpay Test Mode.</p> : <Button disabled={busy} onClick={() => void retryPayment()}>Retry payment</Button>}</Card> : null}
    {!order && !approval ? <Card className="grid gap-5 p-5 sm:p-7"><div className="grid gap-3">{cart.items.map((item) => <div className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm" key={item.productId}><span>{item.name} <span className="text-slate-400">x {item.quantity}</span></span><strong>{cart.currency} {item.subtotal}</strong></div>)}</div><div className="flex justify-between border-t pt-4 text-lg"><span>Total</span><strong>{cart.currency} {cart.subtotal}</strong></div><Button disabled={busy} onClick={() => void createOrder()}>{busy ? 'Checking policy...' : 'Continue to payment'}</Button><p className="text-xs text-slate-500">Stock, price, total, policy, and payment status are verified by AIsle.</p></Card> : null}
  </section>;
}
